# Generated by Django 4.2.6 on 2024-01-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('A', 'Asia'), ('T', 'Antartida'), ('E', 'Europa'), ('C', 'Africa'), ('O', 'Oceania'), ('R', 'America')], default='A', max_length=2),
        ),
    ]
