# Generated by Django 4.2.6 on 2024-01-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_country_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('country', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
        ),
    ]
